### ISSUE TITLE
Request for use example

### ISSUE THREAD

**Issue by IlayGussarsky** [blubber/python-drbg#1]
Hi,
Can you please provide an example for how to use the instantiate (using entropy, nonce, personalization string), generate (using entropy) functions using hex inputs?

Thanks a lot.

**Comment by blubber** [comment]
Hi! You really shouldn't be using this for anything at all, it is not safe. This project was meant for my own education.

Python offers several safe and secure ways to generate random bytes, like [`secrets.token_bytes`](https://docs.python.org/3/library/secrets.html#secrets.token_bytes) (or any of the other functions in the secrets module). If you're using a Python version prior to Python 3.6 refer to the chatper on [Random Number](https://docs.python.org/3/library/secrets.html#secrets.token_bytes) in the `os` module.

Again, do not use this module, it's implementation is neither secure nor safe.
